baseURL = "https://prithu.dev/"
languageCode = "en-us"
title = "Prithu Goswami"
#ignoreFiles = [ "snippets" ]

[params]
    [params.author]
        name = "Prithu Goswami"
        email = "prithu@prithu.dev"

[markup]
    [markup.highlight]
        noClasses = false

